//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblaccountsl4
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblaccountsl4()
        {
            this.tblaccl4paymenmethods = new HashSet<tblaccl4paymenmethods>();
            this.tblaccountl4accounttype = new HashSet<tblaccountl4accounttype>();
            this.tblconciliationsegmentaccl4fee = new HashSet<tblconciliationsegmentaccl4fee>();
            this.tblincomeitem = new HashSet<tblincomeitem>();
            this.tblsegmentaccl4 = new HashSet<tblsegmentaccl4>();
            this.tbluseraccl4 = new HashSet<tbluseraccl4>();
            this.tblinvoiceditem = new HashSet<tblinvoiceditem>();
        }
    
        public int idAccountl4 { get; set; }
        public int idAccountl3 { get; set; }
        public string accountl4name { get; set; }
        public string accountl4description { get; set; }
        public Nullable<bool> accountl4active { get; set; }
        public int accountl4order { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblaccl4paymenmethods> tblaccl4paymenmethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblaccountl4accounttype> tblaccountl4accounttype { get; set; }
        public virtual tblaccountsl3 tblaccountsl3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblconciliationsegmentaccl4fee> tblconciliationsegmentaccl4fee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblincomeitem> tblincomeitem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblsegmentaccl4> tblsegmentaccl4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbluseraccl4> tbluseraccl4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblinvoiceditem> tblinvoiceditem { get; set; }
    }
}
