//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblaccountsl1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblaccountsl1()
        {
            this.tblaccountsl2 = new HashSet<tblaccountsl2>();
        }
    
        public int idaccountl1 { get; set; }
        public string accountl1name { get; set; }
        public string accountl1description { get; set; }
        public Nullable<bool> accountl1active { get; set; }
        public int accountl1order { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblaccountsl2> tblaccountsl2 { get; set; }
    }
}
