//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblaccountsl2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblaccountsl2()
        {
            this.tblaccountsl3 = new HashSet<tblaccountsl3>();
        }
    
        public int idaccountl2 { get; set; }
        public int idaccountl1 { get; set; }
        public string accountl2name { get; set; }
        public string accountl2description { get; set; }
        public Nullable<bool> accountl2active { get; set; }
        public int accountl2order { get; set; }
    
        public virtual tblaccountsl1 tblaccountsl1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblaccountsl3> tblaccountsl3 { get; set; }
    }
}
