//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbankaccountsourcedata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblbankaccountsourcedata()
        {
            this.tblbankaccountsourcedatatypes = new HashSet<tblbankaccountsourcedatatypes>();
        }
    
        public int idbankaccountsourcedata { get; set; }
        public int idbaccount { get; set; }
        public int idsourcedata { get; set; }
        public System.DateTime sourcedatadatestart { get; set; }
    
        public virtual tblbankaccount tblbankaccount { get; set; }
        public virtual tblsourcedata tblsourcedata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbankaccountsourcedatatypes> tblbankaccountsourcedatatypes { get; set; }
    }
}
