//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbankstatements2Log
    {
        public int Log_Id { get; set; }
        public Nullable<System.DateTime> Log_Date { get; set; }
        public Nullable<int> Log_User { get; set; }
        public string Log_Obs { get; set; }
        public long idBankStatements2 { get; set; }
        public int idBAccount { get; set; }
        public int idMovementType { get; set; }
        public System.DateTime bankstatements2AplicationDate { get; set; }
        public string bankstatements2Concept { get; set; }
        public Nullable<decimal> bankstatements2Charge { get; set; }
        public Nullable<decimal> bankstatements2Pay { get; set; }
        public Nullable<int> bankstatements2CreatedBy { get; set; }
        public Nullable<System.DateTime> bankstatements2CreatedOn { get; set; }
        public Nullable<int> bankstatements2UpdatedBy { get; set; }
        public Nullable<System.DateTime> bankstatements2UpdatedOn { get; set; }
    }
}
