//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbankstat2purchase
    {
        public long idBankStat2Purchase { get; set; }
        public int idPaymentPurchase { get; set; }
        public long idBankStatements2 { get; set; }
    
        public virtual tblpaymentspurchases tblpaymentspurchases { get; set; }
        public virtual tblbankstatements2 tblbankstatements2 { get; set; }
    }
}
