//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbankstatements2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblbankstatements2()
        {
            this.tblbankstat2fondo = new HashSet<tblbankstat2fondo>();
            this.tblbankstat2fondo1 = new HashSet<tblbankstat2fondo>();
            this.tblbankstat2income = new HashSet<tblbankstat2income>();
            this.tblbankstat2invoice = new HashSet<tblbankstat2invoice>();
            this.tblbankstat2parentreserv = new HashSet<tblbankstat2parentreserv>();
            this.tblbankstat2purchase = new HashSet<tblbankstat2purchase>();
            this.tblbankstat2reserv = new HashSet<tblbankstat2reserv>();
        }
    
        public long idBankStatements2 { get; set; }
        public int idBAccount { get; set; }
        public int idMovementType { get; set; }
        public System.DateTime bankstatements2AplicationDate { get; set; }
        public string bankstatements2Concept { get; set; }
        public Nullable<decimal> bankstatements2Charge { get; set; }
        public Nullable<decimal> bankstatements2Pay { get; set; }
        public Nullable<int> bankstatements2CreatedBy { get; set; }
        public Nullable<System.DateTime> bankstatements2CreatedOn { get; set; }
        public Nullable<int> bankstatements2UpdatedBy { get; set; }
        public Nullable<System.DateTime> bankstatements2UpdatedOn { get; set; }
        public bool bankstatements2Reconciled { get; set; }
        public int idBankStatementMethod { get; set; }
        public Nullable<decimal> bankstatements2BankFee { get; set; }
    
        public virtual tblusers tblusers { get; set; }
        public virtual tblusers tblusers1 { get; set; }
        public virtual tblbankaccount tblbankaccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbankstat2fondo> tblbankstat2fondo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbankstat2fondo> tblbankstat2fondo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbankstat2income> tblbankstat2income { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbankstat2invoice> tblbankstat2invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbankstat2parentreserv> tblbankstat2parentreserv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbankstat2purchase> tblbankstat2purchase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbankstat2reserv> tblbankstat2reserv { get; set; }
        public virtual tblbankstatementmethod tblbankstatementmethod { get; set; }
        public virtual tblmovementtype tblmovementtype { get; set; }
    }
}
