//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbatchdetailpre
    {
        public int id { get; set; }
        public Nullable<int> idBatch { get; set; }
        public Nullable<int> idDeliver { get; set; }
        public System.DateTime deliveryDate { get; set; }
        public Nullable<int> idChain { get; set; }
        public Nullable<int> idPartner { get; set; }
        public Nullable<int> idPrefix { get; set; }
        public Nullable<int> initialFolio { get; set; }
        public Nullable<int> lastFolio { get; set; }
        public Nullable<decimal> totalPayment { get; set; }
        public Nullable<int> membershipType { get; set; }
        public System.DateTime batchCreate { get; set; }
    
        public virtual tblpartners tblpartners { get; set; }
        public virtual tblprefixes tblprefixes { get; set; }
        public virtual tblbatch tblbatch { get; set; }
    }
}
