//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbankaccountsourcedatatypes
    {
        public int idbankaccountsourcedatatypes { get; set; }
        public int idbankaccountsourcedata { get; set; }
        public int idtype { get; set; }
    
        public virtual tblbankaccountsourcedata tblbankaccountsourcedata { get; set; }
    }
}
