//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbstaterrors
    {
        public int idBStatError { get; set; }
        public string bStatErrorOperUuid { get; set; }
        public System.DateTime bStatErrorDatetime { get; set; }
        public int bStatErrorConsec { get; set; }
        public int bStatErrorTotal { get; set; }
        public string bStatErrorMessage { get; set; }
        public string bStatErrorDetails { get; set; }
        public int idErrorSeverity { get; set; }
        public int idErrorAction { get; set; }
        public bool bStatErrorHasExcep { get; set; }
        public string bStatErrorExcepMsg { get; set; }
        public string bStatErrorExcepStack { get; set; }
        public int idUser { get; set; }
    
        public virtual tblusers tblusers { get; set; }
        public virtual tblerroraction tblerroraction { get; set; }
        public virtual tblerrorseverity tblerrorseverity { get; set; }
    }
}
