//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbankstateparentreserv
    {
        public long idBankstatParentReserv { get; set; }
        public long idBankStatements { get; set; }
        public int idReservationParentPayment { get; set; }
        public string authCode { get; set; }
        public string cardNumber { get; set; }
    
        public virtual tblbankstatements tblbankstatements { get; set; }
        public virtual tblreservationsparentpayment tblreservationsparentpayment { get; set; }
    }
}
