//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbankstatementmethod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblbankstatementmethod()
        {
            this.tblbankstatements = new HashSet<tblbankstatements>();
            this.tblbankstatements2 = new HashSet<tblbankstatements2>();
        }
    
        public int idBankStatementMethod { get; set; }
        public string bankstatementmethodName { get; set; }
        public string bankstatementmethodShortName { get; set; }
        public string bankstatementmethodDescription { get; set; }
        public bool bankstatementmethodActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbankstatements> tblbankstatements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbankstatements2> tblbankstatements2 { get; set; }
    }
}
