//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbankaccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblbankaccount()
        {
            this.tblbaccounprodttype = new HashSet<tblbaccounprodttype>();
            this.tblbaccounttpv = new HashSet<tblbaccounttpv>();
            this.tblbankaccountsourcedata = new HashSet<tblbankaccountsourcedata>();
            this.tblbankstatements = new HashSet<tblbankstatements>();
            this.tblfondos = new HashSet<tblfondos>();
            this.tblfondos1 = new HashSet<tblfondos>();
            this.tblfondosmaxammount = new HashSet<tblfondosmaxammount>();
            this.tbluserbacount = new HashSet<tbluserbacount>();
            this.tblincomemovement = new HashSet<tblincomemovement>();
            this.tblpayment = new HashSet<tblpayment>();
            this.tblbatch = new HashSet<tblbatch>();
            this.tblbankstatements2 = new HashSet<tblbankstatements2>();
        }
    
        public int idbaccount { get; set; }
        public int idbank { get; set; }
        public int idcurrency { get; set; }
        public int idcompany { get; set; }
        public int idbankaccntclasification { get; set; }
        public string baccountname { get; set; }
        public string baccountshortname { get; set; }
        public string baccountdescription { get; set; }
        public int baccountcreatedby { get; set; }
        public System.DateTime baccountcreateddate { get; set; }
        public int baccountmodifiedby { get; set; }
        public System.DateTime baccountmodifiedon { get; set; }
        public bool baccountactive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbaccounprodttype> tblbaccounprodttype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbaccounttpv> tblbaccounttpv { get; set; }
        public virtual tblbank tblbank { get; set; }
        public virtual tblbankaccntclasification tblbankaccntclasification { get; set; }
        public virtual tblcompanies tblcompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbankaccountsourcedata> tblbankaccountsourcedata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbankstatements> tblbankstatements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblfondos> tblfondos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblfondos> tblfondos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblfondosmaxammount> tblfondosmaxammount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbluserbacount> tbluserbacount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblincomemovement> tblincomemovement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblpayment> tblpayment { get; set; }
        public virtual tblcurrencies tblcurrencies { get; set; }
        public virtual tblusers tblusers { get; set; }
        public virtual tblusers tblusers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbatch> tblbatch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbankstatements2> tblbankstatements2 { get; set; }
    }
}
