//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbaccounttpv
    {
        public int idbaccounttpv { get; set; }
        public int idbaccount { get; set; }
        public int idtpv { get; set; }
        public int baccounttpvcreatedBy { get; set; }
        public System.DateTime baccounttpvcreateddate { get; set; }
        public int baccounttpvupdatedby { get; set; }
        public System.DateTime baccounttpvupdateon { get; set; }
    
        public virtual tblbankaccount tblbankaccount { get; set; }
        public virtual tbltpv tbltpv { get; set; }
        public virtual tblusers tblusers { get; set; }
        public virtual tblusers tblusers1 { get; set; }
    }
}
