//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcompaniescurrencies
    {
        public int idcompaniescurrencies { get; set; }
        public int idcompany { get; set; }
        public int idcurrency { get; set; }
        public bool companiescurrenciesactive { get; set; }
    
        public virtual tblcompanies tblcompanies { get; set; }
        public virtual tblcurrencies tblcurrencies { get; set; }
    }
}
