//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcompanydevelopment
    {
        public int idCompanyDevelopment { get; set; }
        public int idCompany { get; set; }
        public int idHotelChain { get; set; }
    
        public virtual tblcompanies tblcompanies { get; set; }
        public virtual tblhotelchains tblhotelchains { get; set; }
    }
}
