//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcurrencies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblcurrencies()
        {
            this.tblbankaccount = new HashSet<tblbankaccount>();
            this.tblincome = new HashSet<tblincome>();
            this.tblpaymentspurchases = new HashSet<tblpaymentspurchases>();
            this.tblpurchasescancellation = new HashSet<tblpurchasescancellation>();
            this.tblreservationsparent = new HashSet<tblreservationsparent>();
            this.tblreservationsparentcancellation = new HashSet<tblreservationsparentcancellation>();
            this.tblcompaniescurrencies = new HashSet<tblcompaniescurrencies>();
            this.tblinvoice = new HashSet<tblinvoice>();
            this.tblreservationcancellation = new HashSet<tblreservationcancellation>();
        }
    
        public int idCurrency { get; set; }
        public string currencyName { get; set; }
        public string currencyAlphabeticCode { get; set; }
        public string currencyNumericCode { get; set; }
        public Nullable<bool> currencyActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbankaccount> tblbankaccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblincome> tblincome { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblpaymentspurchases> tblpaymentspurchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblpurchasescancellation> tblpurchasescancellation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblreservationsparent> tblreservationsparent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblreservationsparentcancellation> tblreservationsparentcancellation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblcompaniescurrencies> tblcompaniescurrencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblinvoice> tblinvoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblreservationcancellation> tblreservationcancellation { get; set; }
    }
}
