//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcurrencyexchange
    {
        public int idcurrencyexchange { get; set; }
        public int currencyexchangefrom { get; set; }
        public int currencyexchangeto { get; set; }
        public decimal currencyexchangerate { get; set; }
        public System.DateTime currencyexchangedate { get; set; }
    }
}
