//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcompanies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblcompanies()
        {
            this.tblbankaccount = new HashSet<tblbankaccount>();
            this.tblbankstatements = new HashSet<tblbankstatements>();
            this.tblcompanydevelopment = new HashSet<tblcompanydevelopment>();
            this.tblcompanygroupdevelopment = new HashSet<tblcompanygroupdevelopment>();
            this.tblcompanygroupdevelopment1 = new HashSet<tblcompanygroupdevelopment>();
            this.tblcompaniesuppliers = new HashSet<tblcompaniesuppliers>();
            this.tblexpensereportsourcedata = new HashSet<tblexpensereportsourcedata>();
            this.tblextgroupcompanies = new HashSet<tblextgroupcompanies>();
            this.tblincome = new HashSet<tblincome>();
            this.tbltpv = new HashSet<tbltpv>();
            this.tblcompaniescurrencies = new HashSet<tblcompaniescurrencies>();
            this.tblinvoice = new HashSet<tblinvoice>();
            this.tblusercompanies = new HashSet<tblusercompanies>();
        }
    
        public int idcompany { get; set; }
        public string companyname { get; set; }
        public string companyshortname { get; set; }
        public string companyaddress { get; set; }
        public string companytelephone { get; set; }
        public bool companyactive { get; set; }
        public Nullable<int> companyorder { get; set; }
        public Nullable<int> idsegment { get; set; }
        public Nullable<bool> fundsGive { get; set; }
        public Nullable<bool> fundsReceive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbankaccount> tblbankaccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbankstatements> tblbankstatements { get; set; }
        public virtual tblsegment tblsegment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblcompanydevelopment> tblcompanydevelopment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblcompanygroupdevelopment> tblcompanygroupdevelopment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblcompanygroupdevelopment> tblcompanygroupdevelopment1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblcompaniesuppliers> tblcompaniesuppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblexpensereportsourcedata> tblexpensereportsourcedata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblextgroupcompanies> tblextgroupcompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblincome> tblincome { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbltpv> tbltpv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblcompaniescurrencies> tblcompaniescurrencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblinvoice> tblinvoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblusercompanies> tblusercompanies { get; set; }
    }
}
