//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblexpensereportsourcedatatypes
    {
        public int idexpensereportsourcedatatypes { get; set; }
        public int idexpensereportsourcedata { get; set; }
        public int idtype { get; set; }
        public bool expensereportsourcedatatypesactive { get; set; }
    
        public virtual tblexpensereportsourcedata tblexpensereportsourcedata { get; set; }
    }
}
