//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblexpensereportsourcedata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblexpensereportsourcedata()
        {
            this.tblexpensereportsourcedatatypes = new HashSet<tblexpensereportsourcedatatypes>();
        }
    
        public int idexpensereportsourcedata { get; set; }
        public int idcompany { get; set; }
        public int idsourcedata { get; set; }
        public bool expensereportsourcedataactive { get; set; }
    
        public virtual tblcompanies tblcompanies { get; set; }
        public virtual tblsourcedata tblsourcedata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblexpensereportsourcedatatypes> tblexpensereportsourcedatatypes { get; set; }
    }
}
