//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblfondosLog
    {
        public int LogId { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<int> LogUser { get; set; }
        public string LogObs { get; set; }
        public Nullable<int> idFondos { get; set; }
        public int idPaymentMethod { get; set; }
        public int idFinancialMethod { get; set; }
        public System.DateTime fondofechaEntrega { get; set; }
        public System.DateTime fondoFechaInicio { get; set; }
        public System.DateTime fondoFechaFin { get; set; }
        public decimal fondoMonto { get; set; }
        public int fondoCreatedby { get; set; }
        public System.DateTime fondoCreationDate { get; set; }
        public string fondoComments { get; set; }
        public decimal fondoFee { get; set; }
        public Nullable<long> fondoInvoice { get; set; }
        public Nullable<int> idFinanceType { get; set; }
    }
}
