//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblfondosmaxammount
    {
        public int idFondosMax { get; set; }
        public int idBAccount { get; set; }
        public decimal fondosmaxAmmount { get; set; }
        public string fondosmaxDescription { get; set; }
        public int fondosmaxCreatedby { get; set; }
        public System.DateTime fondosmaxCreationDate { get; set; }
    
        public virtual tblbankaccount tblbankaccount { get; set; }
        public virtual tblusers tblusers { get; set; }
    }
}
