//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblfondos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblfondos()
        {
            this.tblbankstat2fondo = new HashSet<tblbankstat2fondo>();
        }
    
        public int idFondos { get; set; }
        public int idPaymentMethod { get; set; }
        public int idFinancialMethod { get; set; }
        public System.DateTime fondofechaEntrega { get; set; }
        public System.DateTime fondoFechaInicio { get; set; }
        public System.DateTime fondoFechaFin { get; set; }
        public decimal fondoMonto { get; set; }
        public int fondoCreatedby { get; set; }
        public System.DateTime fondoCreationDate { get; set; }
        public string fondoComments { get; set; }
        public decimal fondoFee { get; set; }
        public Nullable<long> fondoInvoice { get; set; }
        public Nullable<int> idFinanceType { get; set; }
    
        public virtual tblbankaccount tblbankaccount { get; set; }
        public virtual tblbankaccount tblbankaccount1 { get; set; }
        public virtual tblfinancetype tblfinancetype { get; set; }
        public virtual tblusers tblusers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbankstat2fondo> tblbankstat2fondo { get; set; }
    }
}
