//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblhotelchains
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblhotelchains()
        {
            this.tblcompanydevelopment = new HashSet<tblcompanydevelopment>();
            this.tblpartners = new HashSet<tblpartners>();
        }
    
        public int idHotelChain { get; set; }
        public string hotelChainName { get; set; }
        public string hotelChainAbbrev { get; set; }
        public bool hotelChainActive { get; set; }
        public Nullable<bool> certificateActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblcompanydevelopment> tblcompanydevelopment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblpartners> tblpartners { get; set; }
    }
}
