//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblincome
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblincome()
        {
            this.tblincomecomments = new HashSet<tblincomecomments>();
            this.tblincomeitem = new HashSet<tblincomeitem>();
            this.tblincomeattach = new HashSet<tblincomeattach>();
            this.tblincomemovement = new HashSet<tblincomemovement>();
        }
    
        public long idincome { get; set; }
        public int idcompany { get; set; }
        public int idcurrency { get; set; }
        public System.DateTime incomeapplicationdate { get; set; }
        public int incomenumber { get; set; }
        public int incomecreatedby { get; set; }
        public System.DateTime incomecreactiondate { get; set; }
        public int incomeupdatedby { get; set; }
        public System.DateTime incometupdateon { get; set; }
    
        public virtual tblcompanies tblcompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblincomecomments> tblincomecomments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblincomeitem> tblincomeitem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblincomeattach> tblincomeattach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblincomemovement> tblincomemovement { get; set; }
        public virtual tblcurrencies tblcurrencies { get; set; }
        public virtual tblusers tblusers { get; set; }
        public virtual tblusers tblusers1 { get; set; }
    }
}
