//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblinvoiceditemLog
    {
        public int LogId { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<int> LogUser { get; set; }
        public string LogObs { get; set; }
        public int idinvoiceitem { get; set; }
        public int idinvoice { get; set; }
        public int idaccl4 { get; set; }
        public int idinvoiceitemstatus { get; set; }
        public int Iduser { get; set; }
        public Nullable<decimal> invoiceditemsubtotal { get; set; }
        public string description { get; set; }
        public Nullable<bool> deleted { get; set; }
        public bool invoiceditemistax { get; set; }
        public decimal invoiceditemtaxes { get; set; }
        public string invoiceditembillidentifier { get; set; }
        public int idsupplier { get; set; }
        public string invoiceditemsupplierother { get; set; }
        public decimal invoiceditemothertaxesammount { get; set; }
        public bool invoiceditemsingleexibitionpayment { get; set; }
        public int idbudgettype { get; set; }
    }
}
