//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblincomecomments
    {
        public int idincomecomment { get; set; }
        public long idincome { get; set; }
        public int iduser { get; set; }
        public string invcomeCommentdescription { get; set; }
        public System.DateTime incomeCommentcreactiondate { get; set; }
    
        public virtual tblincome tblincome { get; set; }
        public virtual tblusers tblusers { get; set; }
    }
}
