//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblincomeLog
    {
        public long LogId { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<int> LogUser { get; set; }
        public string LogObs { get; set; }
        public long idincome { get; set; }
        public int idcompany { get; set; }
        public int idcurrency { get; set; }
        public System.DateTime incomeapplicationdate { get; set; }
        public int incomenumber { get; set; }
        public int incomecreatedby { get; set; }
        public System.DateTime incomecreactionDate { get; set; }
        public int incomeupdatedby { get; set; }
        public System.DateTime incometupdateon { get; set; }
    }
}
