//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblinvoiceattach
    {
        public int idinvoiceattach { get; set; }
        public long idinvoice { get; set; }
        public int idattach { get; set; }
        public string invoiceattachname { get; set; }
        public string invoiceattachdirectory { get; set; }
        public string invoiceattachcontenttype { get; set; }
        public int invoiceattachuserlastchange { get; set; }
        public Nullable<System.DateTime> invoiceattachdatelastchange { get; set; }
        public bool invoiceattachactive { get; set; }
        public string invoiceattachshortname { get; set; }
    
        public virtual tblattachments tblattachments { get; set; }
        public virtual tblinvoice tblinvoice { get; set; }
        public virtual tblusers tblusers { get; set; }
    }
}
