//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblincomemovement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblincomemovement()
        {
            this.tblbankstateincome = new HashSet<tblbankstateincome>();
            this.tblbankstat2income = new HashSet<tblbankstat2income>();
        }
    
        public long idincomeMovement { get; set; }
        public long idincome { get; set; }
        public int idbaccount { get; set; }
        public int idbankaccnttype { get; set; }
        public Nullable<int> idtpv { get; set; }
        public string incomemovcard { get; set; }
        public System.DateTime incomemovapplicationdate { get; set; }
        public decimal incomemovchargedamount { get; set; }
        public string incomemovauthref { get; set; }
        public System.DateTime incomemovcreationdate { get; set; }
        public int incomemovcreatedby { get; set; }
        public System.DateTime incomemovupdatedon { get; set; }
        public int incomemovupdatedby { get; set; }
        public string incomemovauthcode { get; set; }
    
        public virtual tblbankaccount tblbankaccount { get; set; }
        public virtual tblbankprodttype tblbankprodttype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbankstateincome> tblbankstateincome { get; set; }
        public virtual tblincome tblincome { get; set; }
        public virtual tbltpv tbltpv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbankstat2income> tblbankstat2income { get; set; }
    }
}
