//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblinvoiceitemstatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblinvoiceitemstatus()
        {
            this.tblincomeitem = new HashSet<tblincomeitem>();
            this.tblinvoiceditem = new HashSet<tblinvoiceditem>();
        }
    
        public int idinvoiceItemstatus { get; set; }
        public string invoicestatusname { get; set; }
        public string invoicestatusshortname { get; set; }
        public Nullable<bool> invoicestatusactive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblincomeitem> tblincomeitem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblinvoiceditem> tblinvoiceditem { get; set; }
    }
}
