//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblinvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblinvoice()
        {
            this.tblinvoicecomments = new HashSet<tblinvoicecomments>();
            this.tblinvoiceattach = new HashSet<tblinvoiceattach>();
            this.tblinvoiceditem = new HashSet<tblinvoiceditem>();
            this.tblpayment = new HashSet<tblpayment>();
        }
    
        public long idinvoice { get; set; }
        public int idcompany { get; set; }
        public Nullable<int> idcurrency { get; set; }
        public System.DateTime invoicedate { get; set; }
        public int invoicenumber { get; set; }
        public int invoicecreatedby { get; set; }
        public System.DateTime invoicecreateon { get; set; }
        public int invoiceupdatedby { get; set; }
        public System.DateTime invoiceupdateon { get; set; }
    
        public virtual tblcompanies tblcompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblinvoicecomments> tblinvoicecomments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblinvoiceattach> tblinvoiceattach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblinvoiceditem> tblinvoiceditem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblpayment> tblpayment { get; set; }
        public virtual tblcurrencies tblcurrencies { get; set; }
        public virtual tblusers tblusers { get; set; }
        public virtual tblusers tblusers1 { get; set; }
    }
}
