//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblmembers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblmembers()
        {
            this.tblreservations = new HashSet<tblreservations>();
        }
    
        public int idMember { get; set; }
        public Nullable<int> idCountry { get; set; }
        public int idMembership { get; set; }
        public string memberFirstName { get; set; }
        public string memberLastName { get; set; }
        public Nullable<System.DateTime> memberBirthday { get; set; }
        public string memberStreetAddress { get; set; }
        public string memberCity { get; set; }
        public string memberState { get; set; }
        public string memberZipCode { get; set; }
        public string memberTelephoneHome { get; set; }
        public string memberTelephoneMobile { get; set; }
        public string memberMail { get; set; }
        public Nullable<bool> memberActive { get; set; }
        public Nullable<int> memberFolio { get; set; }
        public string memberFacebookAccount { get; set; }
        public string memberInstagramAccount { get; set; }
        public string memberWhatsapp { get; set; }
        public string schedulePreference { get; set; }
    
        public virtual tblmemberships tblmemberships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblreservations> tblreservations { get; set; }
    }
}
