//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblprofaccclass3
    {
        public int idprofaccclass3 { get; set; }
        public int idaccountl3 { get; set; }
        public int idprofileaccount { get; set; }
        public int profaccclassuserlastchange { get; set; }
        public Nullable<System.DateTime> profaccclassdatelastchange { get; set; }
    
        public virtual tblaccountsl3 tblaccountsl3 { get; set; }
        public virtual tblprofilesaccounts tblprofilesaccounts { get; set; }
    }
}
