//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpurchases
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblpurchases()
        {
            this.tblpaymentspurchases = new HashSet<tblpaymentspurchases>();
            this.tblpurchasescancellation = new HashSet<tblpurchasescancellation>();
            this.tblbatchdetail = new HashSet<tblbatchdetail>();
        }
    
        public int idPurchase { get; set; }
        public int idPartner { get; set; }
        public int idMembership { get; set; }
        public int idMembershipType { get; set; }
        public Nullable<System.DateTime> purchaseStartDate { get; set; }
        public Nullable<System.DateTime> purchaseDate { get; set; }
        public Nullable<int> purchaseYears { get; set; }
        public Nullable<int> purchaseMonths { get; set; }
        public Nullable<decimal> purchaseSellPrice { get; set; }
        public Nullable<decimal> purchaseProductionCost { get; set; }
        public string purchasePaymentReference { get; set; }
        public Nullable<bool> isRenewalPurchase { get; set; }
        public Nullable<int> idRenewalCost { get; set; }
        public Nullable<int> saleType { get; set; }
        public string salePerson { get; set; }
        public Nullable<int> salePerson_ILWP { get; set; }
        public Nullable<int> points_ILWP { get; set; }
        public Nullable<decimal> pricePurchase { get; set; }
        public Nullable<int> idPurchaseStatus { get; set; }
        public Nullable<int> idRequest { get; set; }
    
        public virtual tblmemberships tblmemberships { get; set; }
        public virtual tblpartners tblpartners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblpaymentspurchases> tblpaymentspurchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblpurchasescancellation> tblpurchasescancellation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbatchdetail> tblbatchdetail { get; set; }
    }
}
