//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpaymentspurchases
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblpaymentspurchases()
        {
            this.tblbankstatepurchase = new HashSet<tblbankstatepurchase>();
            this.tblbankstat2purchase = new HashSet<tblbankstat2purchase>();
        }
    
        public int idPaymentPurchase { get; set; }
        public Nullable<int> idPurchase { get; set; }
        public Nullable<int> idPaymentType { get; set; }
        public Nullable<long> cardDigits { get; set; }
        public Nullable<int> idCurrency { get; set; }
        public Nullable<int> terminal { get; set; }
        public Nullable<decimal> paymentCost { get; set; }
        public Nullable<decimal> exchangeRate { get; set; }
        public Nullable<System.DateTime> paymentDate { get; set; }
        public string authCode { get; set; }
    
        public virtual tblcurrencies tblcurrencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbankstatepurchase> tblbankstatepurchase { get; set; }
        public virtual tblpurchases tblpurchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbankstat2purchase> tblbankstat2purchase { get; set; }
    }
}
