//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpaymentLog
    {
        public int LogId { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<int> LogUser { get; set; }
        public string LogObs { get; set; }
        public long idPayment { get; set; }
        public int idInvoice { get; set; }
        public int idBAccount { get; set; }
        public int idBankAccntType { get; set; }
        public System.DateTime applicationDate { get; set; }
        public decimal chargedAmount { get; set; }
        public string authRef { get; set; }
        public System.DateTime creationDate { get; set; }
        public int createdBy { get; set; }
        public System.DateTime updatedOn { get; set; }
        public int updatedBy { get; set; }
        public Nullable<int> paymentdeletedby { get; set; }
        public Nullable<System.DateTime> paymentdeletedon { get; set; }
    }
}
