//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblreservations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblreservations()
        {
            this.tblreservationspayment = new HashSet<tblreservationspayment>();
            this.tblreservationcancellation = new HashSet<tblreservationcancellation>();
        }
    
        public int idReservation { get; set; }
        public int idMembership { get; set; }
        public Nullable<int> idHotelType { get; set; }
        public Nullable<int> idCountry { get; set; }
        public Nullable<int> idReservationStatus { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> idPartner { get; set; }
        public Nullable<int> idPaymentForm { get; set; }
        public Nullable<int> idChannel { get; set; }
        public Nullable<int> idServiceType { get; set; }
        public string reservationHotelName { get; set; }
        public string reservationGuestName { get; set; }
        public Nullable<System.DateTime> reservationCheckIn { get; set; }
        public Nullable<System.DateTime> reservationCheckOut { get; set; }
        public string reservationCity { get; set; }
        public Nullable<int> reservationAdults { get; set; }
        public Nullable<int> reservationChildren { get; set; }
        public string reservationChildrenAges { get; set; }
        public string reservationComments { get; set; }
        public string reservationDetails { get; set; }
        public string reservationExternalRef { get; set; }
        public string reservationInternalLocator { get; set; }
        public string reservationCancelationPolicy { get; set; }
        public Nullable<decimal> reservationProductionCost { get; set; }
        public Nullable<decimal> reservationSellPrice { get; set; }
        public Nullable<int> idSubcategory { get; set; }
        public Nullable<int> idCertificateAmount { get; set; }
        public Nullable<int> idRefundType { get; set; }
        public Nullable<int> idMember { get; set; }
        public Nullable<int> idBeneficiary { get; set; }
        public Nullable<int> idCity { get; set; }
        public Nullable<int> idSupplier { get; set; }
        public Nullable<int> idSupplierAccount { get; set; }
        public Nullable<System.DateTime> purchaseDate { get; set; }
        public Nullable<System.DateTime> cancellationDeadline { get; set; }
        public Nullable<int> reservationInfants { get; set; }
        public string reservationInfantAges { get; set; }
        public Nullable<int> memberCharge { get; set; }
        public Nullable<long> cardDigits { get; set; }
        public Nullable<decimal> expediaTAAP { get; set; }
        public Nullable<decimal> bankCommision { get; set; }
        public Nullable<int> supplierPayment { get; set; }
        public Nullable<int> memberPayment { get; set; }
        public string referenceCode { get; set; }
        public Nullable<decimal> reservationRealPrice { get; set; }
        public Nullable<decimal> reservationCommission { get; set; }
        public Nullable<System.DateTime> eventDate { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<int> idReservationGroup { get; set; }
        public Nullable<int> idRequest { get; set; }
        public Nullable<int> idState { get; set; }
        public string cityName { get; set; }
        public Nullable<int> idReservationType { get; set; }
        public string numberTicket { get; set; }
    
        public virtual tblmembers tblmembers { get; set; }
        public virtual tblmemberships tblmemberships { get; set; }
        public virtual tblpartners tblpartners { get; set; }
        public virtual tblPaymentForms tblPaymentForms { get; set; }
        public virtual tblPaymentForms tblPaymentForms1 { get; set; }
        public virtual tblPaymentForms tblPaymentForms2 { get; set; }
        public virtual tblSuppliers tblSuppliers { get; set; }
        public virtual tbltpv tbltpv { get; set; }
        public virtual tblusers tblusers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblreservationspayment> tblreservationspayment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblreservationcancellation> tblreservationcancellation { get; set; }
    }
}
