//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblreservationspayment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblreservationspayment()
        {
            this.tblbankstatereserv = new HashSet<tblbankstatereserv>();
            this.tblbankstat2reserv = new HashSet<tblbankstat2reserv>();
        }
    
        public int idReservationPayment { get; set; }
        public Nullable<int> idReservation { get; set; }
        public Nullable<int> idPaymentType { get; set; }
        public Nullable<long> cardDigits { get; set; }
        public Nullable<int> idCurrency { get; set; }
        public Nullable<int> terminal { get; set; }
        public Nullable<decimal> reservationPaymentCost { get; set; }
        public Nullable<decimal> exchangeRate { get; set; }
        public Nullable<System.DateTime> reservationPaymentDate { get; set; }
        public string authCode { get; set; }
    
        public virtual tblreservations tblreservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbankstatereserv> tblbankstatereserv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbankstat2reserv> tblbankstat2reserv { get; set; }
    }
}
