//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblreservationsparent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblreservationsparent()
        {
            this.tblreservationsparentcancellation = new HashSet<tblreservationsparentcancellation>();
            this.tblreservationsparentpayment = new HashSet<tblreservationsparentpayment>();
        }
    
        public int idReservationParent { get; set; }
        public string reservationParentGuestName { get; set; }
        public Nullable<System.DateTime> reservationParentCheckIn { get; set; }
        public Nullable<System.DateTime> reservationParentCheckOut { get; set; }
        public Nullable<int> idReservationStatus { get; set; }
        public Nullable<int> idCountry { get; set; }
        public Nullable<int> idState { get; set; }
        public string cityName { get; set; }
        public Nullable<int> idServiceType { get; set; }
        public Nullable<int> idPaymentForm { get; set; }
        public Nullable<int> idChannel { get; set; }
        public string reservationParentInternalLocator { get; set; }
        public string reservationParentExternalRef { get; set; }
        public string reservationParentHotelName { get; set; }
        public Nullable<int> reservationParentAdults { get; set; }
        public Nullable<int> reservationParentChildren { get; set; }
        public string reservationParentComments { get; set; }
        public Nullable<decimal> reservationParentCost { get; set; }
        public Nullable<System.DateTime> reservationParentTimeStamp { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> idSubcategory { get; set; }
        public Nullable<int> idRequest { get; set; }
        public Nullable<int> idPartner { get; set; }
        public Nullable<int> idSupplier { get; set; }
        public Nullable<int> idSupplierAccount { get; set; }
        public Nullable<System.DateTime> reservationParentPurchaseDate { get; set; }
        public Nullable<System.DateTime> cancellationDeadline { get; set; }
        public string reservationParentChildrenAges { get; set; }
        public Nullable<int> reservationParentInfants { get; set; }
        public string reservationParentInfantAges { get; set; }
        public Nullable<int> memberCharge { get; set; }
        public Nullable<long> cardDigits { get; set; }
        public Nullable<decimal> expediaTAAP { get; set; }
        public Nullable<decimal> bankCommision { get; set; }
        public Nullable<int> supplierPayment { get; set; }
        public Nullable<int> memberPayment { get; set; }
        public string referenceCode { get; set; }
        public Nullable<int> idCurrency { get; set; }
        public Nullable<decimal> reservationParentSellPrice { get; set; }
        public Nullable<decimal> reservationParentRealPrice { get; set; }
        public Nullable<decimal> reservationParentCommission { get; set; }
        public Nullable<int> idReservationParentType { get; set; }
        public Nullable<int> idCompany { get; set; }
        public Nullable<System.DateTime> eventDate { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string numberTicket { get; set; }
    
        public virtual tblcurrencies tblcurrencies { get; set; }
        public virtual tblPaymentForms tblPaymentForms { get; set; }
        public virtual tblPaymentForms tblPaymentForms1 { get; set; }
        public virtual tblPaymentForms tblPaymentForms2 { get; set; }
        public virtual tblPaymentForms tblPaymentForms3 { get; set; }
        public virtual tblSuppliers tblSuppliers { get; set; }
        public virtual tblusers tblusers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblreservationsparentcancellation> tblreservationsparentcancellation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblreservationsparentpayment> tblreservationsparentpayment { get; set; }
    }
}
