//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblreservationsparentpayment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblreservationsparentpayment()
        {
            this.tblbankstateparentreserv = new HashSet<tblbankstateparentreserv>();
            this.tblbankstat2parentreserv = new HashSet<tblbankstat2parentreserv>();
        }
    
        public int idReservationParentPayment { get; set; }
        public Nullable<int> idReservationParent { get; set; }
        public Nullable<int> idPaymentType { get; set; }
        public Nullable<long> cardDigits { get; set; }
        public Nullable<int> idCurrency { get; set; }
        public Nullable<int> terminal { get; set; }
        public Nullable<decimal> reservationPaymentCost { get; set; }
        public Nullable<decimal> exchangeRate { get; set; }
        public Nullable<System.DateTime> reservationPaymentDate { get; set; }
        public string authCode { get; set; }
    
        public virtual tblreservationsparent tblreservationsparent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbankstateparentreserv> tblbankstateparentreserv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbankstat2parentreserv> tblbankstat2parentreserv { get; set; }
    }
}
