//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSuppliers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSuppliers()
        {
            this.tblreservations = new HashSet<tblreservations>();
            this.tblreservationsparent = new HashSet<tblreservationsparent>();
            this.tblcompaniesuppliers = new HashSet<tblcompaniesuppliers>();
            this.tblinvoiceditem = new HashSet<tblinvoiceditem>();
        }
    
        public int idSupplier { get; set; }
        public string supplierName { get; set; }
        public Nullable<int> supplierOrder { get; set; }
        public bool supplierHasAccounts { get; set; }
        public bool supplierActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblreservations> tblreservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblreservationsparent> tblreservationsparent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblcompaniesuppliers> tblcompaniesuppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblinvoiceditem> tblinvoiceditem { get; set; }
    }
}
