//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsegment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblsegment()
        {
            this.tblcompanies = new HashSet<tblcompanies>();
            this.tblconciliationsegmentaccl4fee = new HashSet<tblconciliationsegmentaccl4fee>();
            this.tblsegmentaccl4 = new HashSet<tblsegmentaccl4>();
        }
    
        public int idsegment { get; set; }
        public string segmentname { get; set; }
        public string Segmentshortname { get; set; }
        public string segmentdescription { get; set; }
        public bool segmentactive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblcompanies> tblcompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblconciliationsegmentaccl4fee> tblconciliationsegmentaccl4fee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblsegmentaccl4> tblsegmentaccl4 { get; set; }
    }
}
