//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltpv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbltpv()
        {
            this.tblbaccounttpv = new HashSet<tblbaccounttpv>();
            this.tblbankstatements = new HashSet<tblbankstatements>();
            this.tblbankstatementsdet = new HashSet<tblbankstatementsdet>();
            this.tblincomemovement = new HashSet<tblincomemovement>();
            this.tblreservations = new HashSet<tblreservations>();
        }
    
        public int idtpv { get; set; }
        public string tpvname { get; set; }
        public string tpvdescription { get; set; }
        public string tpvidlocation { get; set; }
        public int tpvcreatedby { get; set; }
        public System.DateTime tpvcreateddate { get; set; }
        public int tpvmodifiedby { get; set; }
        public System.DateTime tpvmodifiedon { get; set; }
        public bool tpvactive { get; set; }
        public Nullable<int> iddeposittype { get; set; }
        public Nullable<int> idphysicallyat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbaccounttpv> tblbaccounttpv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbankstatements> tblbankstatements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbankstatementsdet> tblbankstatementsdet { get; set; }
        public virtual tblcompanies tblcompanies { get; set; }
        public virtual tbldeposittypes tbldeposittypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblincomemovement> tblincomemovement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblreservations> tblreservations { get; set; }
    }
}
