//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblusers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblusers()
        {
            this.tblreservations = new HashSet<tblreservations>();
            this.tblreservationsparent = new HashSet<tblreservationsparent>();
            this.tblbaccounttpv = new HashSet<tblbaccounttpv>();
            this.tblbaccounttpv1 = new HashSet<tblbaccounttpv>();
            this.tblbankaccount = new HashSet<tblbankaccount>();
            this.tblbankaccount1 = new HashSet<tblbankaccount>();
            this.tblfondos = new HashSet<tblfondos>();
            this.tblfondosmaxammount = new HashSet<tblfondosmaxammount>();
            this.tblincome = new HashSet<tblincome>();
            this.tblincome1 = new HashSet<tblincome>();
            this.tblincomecomments = new HashSet<tblincomecomments>();
            this.tblincomeitem = new HashSet<tblincomeitem>();
            this.tblinvoice = new HashSet<tblinvoice>();
            this.tblinvoice1 = new HashSet<tblinvoice>();
            this.tblinvoicecomments = new HashSet<tblinvoicecomments>();
            this.tbluseraccl4 = new HashSet<tbluseraccl4>();
            this.tbluserbacount = new HashSet<tbluserbacount>();
            this.tblincomeattach = new HashSet<tblincomeattach>();
            this.tblinvoiceattach = new HashSet<tblinvoiceattach>();
            this.tblinvoiceditem = new HashSet<tblinvoiceditem>();
            this.tblusercompanies = new HashSet<tblusercompanies>();
            this.tbluserpermissions = new HashSet<tbluserpermissions>();
            this.tblbstaterrors = new HashSet<tblbstaterrors>();
            this.tblbankstatements2 = new HashSet<tblbankstatements2>();
            this.tblbankstatements21 = new HashSet<tblbankstatements2>();
        }
    
        public int idUser { get; set; }
        public long idPermission { get; set; }
        public int idProfile { get; set; }
        public string userLoginName { get; set; }
        public string userPassword { get; set; }
        public string userPersonName { get; set; }
        public string userPersonLastName { get; set; }
        public string userEmail { get; set; }
        public bool userActive { get; set; }
        public Nullable<int> idprofileaccount { get; set; }
        public string passwordHash { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblreservations> tblreservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblreservationsparent> tblreservationsparent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbaccounttpv> tblbaccounttpv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbaccounttpv> tblbaccounttpv1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbankaccount> tblbankaccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbankaccount> tblbankaccount1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblfondos> tblfondos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblfondosmaxammount> tblfondosmaxammount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblincome> tblincome { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblincome> tblincome1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblincomecomments> tblincomecomments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblincomeitem> tblincomeitem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblinvoice> tblinvoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblinvoice> tblinvoice1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblinvoicecomments> tblinvoicecomments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbluseraccl4> tbluseraccl4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbluserbacount> tbluserbacount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblincomeattach> tblincomeattach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblinvoiceattach> tblinvoiceattach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblinvoiceditem> tblinvoiceditem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblusercompanies> tblusercompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbluserpermissions> tbluserpermissions { get; set; }
        public virtual tblprofilesaccounts tblprofilesaccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbstaterrors> tblbstaterrors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbankstatements2> tblbankstatements2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbankstatements2> tblbankstatements21 { get; set; }
    }
}
