//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbluserpermissions
    {
        public int IdUserPermission { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> idPermission { get; set; }
        public Nullable<bool> userpermissionActive { get; set; }
    
        public virtual tblpermissions tblpermissions { get; set; }
        public virtual tblusers tblusers { get; set; }
    }
}
