//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbluserbacount
    {
        public int iduserbacount { get; set; }
        public int iduser { get; set; }
        public int idbaccount { get; set; }
        public int userbacountcreatedby { get; set; }
        public System.DateTime userbacountcreationdate { get; set; }
        public bool userbacountactive { get; set; }
    
        public virtual tblbankaccount tblbankaccount { get; set; }
        public virtual tblusers tblusers { get; set; }
    }
}
