//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblusercompanies
    {
        public int idusercompany { get; set; }
        public int idcompany { get; set; }
        public int iduser { get; set; }
        public int usercompanyuserlastchange { get; set; }
        public Nullable<System.DateTime> usercompanydatelastchange { get; set; }
        public Nullable<bool> usercompanyactive { get; set; }
    
        public virtual tblcompanies tblcompanies { get; set; }
        public virtual tblusers tblusers { get; set; }
    }
}
