//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAworldpass.VTACore.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vtclubdbEntities : DbContext
    {
        public vtclubdbEntities()
            : base("name=vtclubdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblmemberships> tblmemberships { get; set; }
        public virtual DbSet<tblaccl4paymenmethods> tblaccl4paymenmethods { get; set; }
        public virtual DbSet<tblaccountl4accounttype> tblaccountl4accounttype { get; set; }
        public virtual DbSet<tblaccountsl1> tblaccountsl1 { get; set; }
        public virtual DbSet<tblaccountsl2> tblaccountsl2 { get; set; }
        public virtual DbSet<tblaccountsl3> tblaccountsl3 { get; set; }
        public virtual DbSet<tblaccountsl4> tblaccountsl4 { get; set; }
        public virtual DbSet<tblaccounttypereport> tblaccounttypereport { get; set; }
        public virtual DbSet<tblattachments> tblattachments { get; set; }
        public virtual DbSet<tblbaccounprodttype> tblbaccounprodttype { get; set; }
        public virtual DbSet<tblbaccounttpv> tblbaccounttpv { get; set; }
        public virtual DbSet<tblbank> tblbank { get; set; }
        public virtual DbSet<tblbankaccntclasification> tblbankaccntclasification { get; set; }
        public virtual DbSet<tblbankaccount> tblbankaccount { get; set; }
        public virtual DbSet<tblbankaccountsourcedata> tblbankaccountsourcedata { get; set; }
        public virtual DbSet<tblbankaccountsourcedatatypes> tblbankaccountsourcedatatypes { get; set; }
        public virtual DbSet<tblbankprodttype> tblbankprodttype { get; set; }
        public virtual DbSet<tblbankstateincome> tblbankstateincome { get; set; }
        public virtual DbSet<tblbankstatementmethod> tblbankstatementmethod { get; set; }
        public virtual DbSet<tblbankstatements> tblbankstatements { get; set; }
        public virtual DbSet<tblbankstatements2Log> tblbankstatements2Log { get; set; }
        public virtual DbSet<tblbankstatementsdet> tblbankstatementsdet { get; set; }
        public virtual DbSet<tblbankstatementsgap> tblbankstatementsgap { get; set; }
        public virtual DbSet<tblbankstatementsLog> tblbankstatementsLog { get; set; }
        public virtual DbSet<tblbankstateparentreserv> tblbankstateparentreserv { get; set; }
        public virtual DbSet<tblbankstatepurchase> tblbankstatepurchase { get; set; }
        public virtual DbSet<tblbankstatereserv> tblbankstatereserv { get; set; }
        public virtual DbSet<tblbugettype> tblbugettype { get; set; }
        public virtual DbSet<tblcompanies> tblcompanies { get; set; }
        public virtual DbSet<tblcompaniescurrencies> tblcompaniescurrencies { get; set; }
        public virtual DbSet<tblcompaniesuppliers> tblcompaniesuppliers { get; set; }
        public virtual DbSet<tblcompanydevelopment> tblcompanydevelopment { get; set; }
        public virtual DbSet<tblcompanygroupdevelopment> tblcompanygroupdevelopment { get; set; }
        public virtual DbSet<tblconciliationsegmentaccl4fee> tblconciliationsegmentaccl4fee { get; set; }
        public virtual DbSet<tblcurrencyexchange> tblcurrencyexchange { get; set; }
        public virtual DbSet<tbldeposittypes> tbldeposittypes { get; set; }
        public virtual DbSet<tblexpensereportsourcedata> tblexpensereportsourcedata { get; set; }
        public virtual DbSet<tblexpensereportsourcedatatypes> tblexpensereportsourcedatatypes { get; set; }
        public virtual DbSet<tblexternalgroup> tblexternalgroup { get; set; }
        public virtual DbSet<tblextgroupcompanies> tblextgroupcompanies { get; set; }
        public virtual DbSet<tblfinancetype> tblfinancetype { get; set; }
        public virtual DbSet<tblfondos> tblfondos { get; set; }
        public virtual DbSet<tblfondosLog> tblfondosLog { get; set; }
        public virtual DbSet<tblfondosmaxammount> tblfondosmaxammount { get; set; }
        public virtual DbSet<tblfondosmaxammountLog> tblfondosmaxammountLog { get; set; }
        public virtual DbSet<tblincome> tblincome { get; set; }
        public virtual DbSet<tblincomeattach> tblincomeattach { get; set; }
        public virtual DbSet<tblincomecomments> tblincomecomments { get; set; }
        public virtual DbSet<tblincomeitem> tblincomeitem { get; set; }
        public virtual DbSet<tblincomeitemLog> tblincomeitemLog { get; set; }
        public virtual DbSet<tblincomeLog> tblincomeLog { get; set; }
        public virtual DbSet<tblincomemovement> tblincomemovement { get; set; }
        public virtual DbSet<tblinvoice> tblinvoice { get; set; }
        public virtual DbSet<tblinvoiceattach> tblinvoiceattach { get; set; }
        public virtual DbSet<tblinvoicecomments> tblinvoicecomments { get; set; }
        public virtual DbSet<tblinvoiceditem> tblinvoiceditem { get; set; }
        public virtual DbSet<tblinvoiceditemLog> tblinvoiceditemLog { get; set; }
        public virtual DbSet<tblinvoiceitemstatus> tblinvoiceitemstatus { get; set; }
        public virtual DbSet<tblinvoiceLog> tblinvoiceLog { get; set; }
        public virtual DbSet<tblparameters> tblparameters { get; set; }
        public virtual DbSet<tblpayment> tblpayment { get; set; }
        public virtual DbSet<tblpaymentLog> tblpaymentLog { get; set; }
        public virtual DbSet<tblpermissions> tblpermissions { get; set; }
        public virtual DbSet<tblprofaccclass3> tblprofaccclass3 { get; set; }
        public virtual DbSet<tblprofilesaccounts> tblprofilesaccounts { get; set; }
        public virtual DbSet<tblsegment> tblsegment { get; set; }
        public virtual DbSet<tblsegmentaccl4> tblsegmentaccl4 { get; set; }
        public virtual DbSet<tblsourcedata> tblsourcedata { get; set; }
        public virtual DbSet<tbltpv> tbltpv { get; set; }
        public virtual DbSet<tbluseraccl4> tbluseraccl4 { get; set; }
        public virtual DbSet<tbluserbacount> tbluserbacount { get; set; }
        public virtual DbSet<tblusercompanies> tblusercompanies { get; set; }
        public virtual DbSet<tbluserpermissions> tbluserpermissions { get; set; }
        public virtual DbSet<tblcurrencies> tblcurrencies { get; set; }
        public virtual DbSet<tblhotelchains> tblhotelchains { get; set; }
        public virtual DbSet<tblmembers> tblmembers { get; set; }
        public virtual DbSet<tblpartners> tblpartners { get; set; }
        public virtual DbSet<tblPaymentForms> tblPaymentForms { get; set; }
        public virtual DbSet<tblpaymentspurchases> tblpaymentspurchases { get; set; }
        public virtual DbSet<tblprefixes> tblprefixes { get; set; }
        public virtual DbSet<tblpurchases> tblpurchases { get; set; }
        public virtual DbSet<tblpurchasescancellation> tblpurchasescancellation { get; set; }
        public virtual DbSet<tblreservations> tblreservations { get; set; }
        public virtual DbSet<tblreservationsparent> tblreservationsparent { get; set; }
        public virtual DbSet<tblreservationsparentpayment> tblreservationsparentpayment { get; set; }
        public virtual DbSet<tblreservationspayment> tblreservationspayment { get; set; }
        public virtual DbSet<tblSuppliers> tblSuppliers { get; set; }
        public virtual DbSet<tblusers> tblusers { get; set; }
        public virtual DbSet<tblreservationsparentcancellation> tblreservationsparentcancellation { get; set; }
        public virtual DbSet<tblincomemovementLog> tblincomemovementLog { get; set; }
        public virtual DbSet<tblparameters1> tblparameters1Set { get; set; }
        public virtual DbSet<tblreservationcancellation> tblreservationcancellation { get; set; }
        public virtual DbSet<tblbstaterrors> tblbstaterrors { get; set; }
        public virtual DbSet<tblerroraction> tblerroraction { get; set; }
        public virtual DbSet<tblerrorseverity> tblerrorseverity { get; set; }
        public virtual DbSet<tblbankstat2fondo> tblbankstat2fondo { get; set; }
        public virtual DbSet<tblbankstat2invoice> tblbankstat2invoice { get; set; }
        public virtual DbSet<tblbankstat2parentreserv> tblbankstat2parentreserv { get; set; }
        public virtual DbSet<tblbankstat2purchase> tblbankstat2purchase { get; set; }
        public virtual DbSet<tblbankstat2reserv> tblbankstat2reserv { get; set; }
        public virtual DbSet<tblmovementtype> tblmovementtype { get; set; }
        public virtual DbSet<tbloperationtype> tbloperationtype { get; set; }
        public virtual DbSet<tblbankstat2income> tblbankstat2income { get; set; }
        public virtual DbSet<tblbatchdetail> tblbatchdetail { get; set; }
        public virtual DbSet<tblbatchdetailpre> tblbatchdetailpre { get; set; }
        public virtual DbSet<tblbatch> tblbatch { get; set; }
        public virtual DbSet<tblbankstatements2> tblbankstatements2 { get; set; }
    }
}
